### ISSUE TITLE
Make wire protocol version a property of request and response headers

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/parsec-interface-rs#41]
Currently code outside the interface is free to set the wire protocol version on requests, despite the fact that the wire protocol version is in strict correlation with the code form of the request header. Just as we limit the magic number and header size, we should limit the version number to be hardcoded in by `RequestHeader`. In that way, wire protocol version would be tied down to the implementation of the header. The version number could then be retrieved, but not set.

**Comment by ionut-arm** [comment]
Thinking about this made me realize that we cannot support multiple header versions in the same service pipeline unless we create a trait that requests have to implement, covering all use cases (e.g. `body()`, `auth()`, `opcode()`), and we refactor the pipeline to handle `Box<dyn Request>`

**Comment by hug-dev** [comment]
It is a very good point, could it be solved for now by putting those fields private?
I like the idea of the trait and is probably the way to go in the future but I think because of the fact that the wire protocol is not meant to change that much in the near future, it might be a bit overkill to implement now.

**Comment by ionut-arm** [comment]
Yeah, it's definitely not worth the time and the added complexity to make requests more generic, but hiding the version fields would be a good addition.

**Comment by ionut-arm** [comment]
We literally [do not allow anything else apart from `1.0` as a version](https://github.com/parallaxsecond/parsec-interface-rs/blob/master/src/requests/request/request_header.rs#L116) - what were we thinking when we left those to be public 😕

**Comment by hug-dev** [comment]
Was that fixed in #43 ?

**Comment by ionut-arm** [comment]
> Was that fixed in #43 ?

Sort of... We still don't have a good plan for how we'll manage version in the future, but we can close this for now and re-discuss in a more generic issue.
